### ISSUE TITLE
Camera Paper error

### ISSUE THREAD

**Issue by IlMicioLetale** [Soufiane2214/sf_camerasecurity#1]
Hi, when im place a "camera_citizen" and add me a "camera_paper" i have this error

Im on QBCore + Oxinv

![camera](https://github.com/Soufiane2214/sf_camerasecurity/assets/121300910/9c58f39d-9da9-4e0a-a67c-077863eeb8c9)

**Comment by Soufiane2214** [comment]
For new not support ox_inventory just wait next update will be released today or tomorrow 
join discord to notify when released : https://discord.gg/WQNGvFY8

**Comment by Soufiane2214** [comment]
you can download new update now its support ox_inventory

**Comment by Soufiane2214** [comment]
Fixed
