### ISSUE TITLE
Quasar inventory issue

### ISSUE THREAD

**Issue by Dejvi1** [Soufiane2214/sf_camerasecurity#5]
Hello, after opening camera view and leaving it the inventory stops opening. Only fix is to completely relog.

**Comment by Soufiane2214** [comment]
i think is a problem from inventory

**Comment by Soufiane2214** [comment]
wait next update soon

**Comment by Soufiane2214** [comment]
fixed you can new download new version from here 
https://github.com/Soufiane2214/sf_camerasecurity/releases/tag/1.5.2
